### ISSUE TITLE
Misplaced .keystore

### ISSUE THREAD

**Issue by jacuerp** [AguaClara/post.visualize#16]
I recently used post.visualizations-release.keystore with alias post_key to attempt to sign and upload the most recent version of our code to the Playstore. The alias "post_key" was refused so I instead used "post" on a whim, which was successful. 

However, after uploading to the Playstore and attempting to publish, I received an error stating that the keystore/alias I used is different from the keystore/alias which was used to upload the original .apk, and cannot be used to update the application.

**Comment by eak24** [comment]
@jacuerp please read the readme... You should be using Cordova to sign your build, which finds the correct key [here]( https://github.com/AguaClara/post.visualize/tree/gh-pages/platforms/android) The password is in the passwords doc. Sorry I hadn't realized you were looking for the key in the drive! Yeah, I had changed that process a while ago :P. I'm storing it in the main repo because it is password protected anyways. Cheers.

**Comment by eak24** [comment]
@jacuerp I finally figured out what happened... You had deleted the Keystore I made in this massive commit you made: 65e76594bcdabe50b4b27a2c5d1ef5287b5bbb09 this makes me nervous... can you please explain what you did in these massive commits? In that one you deleted the POST-release-key.keystore file and I have no idea why.

**Comment by jacuerp** [comment]
@ethan92429 Yeesh, this makes me nervous too, looking back on it. Not sure what I was thinking, or why I did that. I think I did it in preparation for the BOOM showcase, in an effort to make everything work with the visualization design updates we had implemented. Most likely case is that I was sleep deprived and frustrated because I couldn't understand the Jekyll workflow, came up with an aggressive workaround.
