### ISSUE TITLE
Vertical bar idea for graph--display exact values

### ISSUE THREAD

**Issue by sjs334** [AguaClara/post.visualize#7]
Wouldn't it be cool if they could sweep a vertical bar over the data and see what the exact values were?

**Comment by jacuerp** [comment]
@ethan92429 I implemented this and pushed it to mobile if you want to check it out. I'd appreciate some feedback on aesthetics, functionality, and coding practices whenever you've got time. I'd like to actually display the y-values somewhere onscreen but I'm not sure how much liberty I can take with the UI. The current iteration tries to make as few waves as possible and just sneak onto the x-axis without its own slider bar.

**Comment by eak24** [comment]
@jacuerp I just looked at the bar and it seems great! I didn't do a code review, but if it works then I say it's fine! I was getting some NaN errors in the console when I ran it, so you may want to check more carefully for those. Also, I think it might be helpful to show the actual value as a tooltip at the point rather than just the horizontal lines, so we can provide them immediately with precise values. How does that sound? Also, would you be interested in meeting over skype sometime soon? I emailed you recently about this but I'm not sure it went through. We could also set up a few meetings with Walker and Jon and Nicki to help us all get on the same page! Hope you have a great weekend 👍

**Comment by jacuerp** [comment]
@ethan92429 
Thanks! 
Yeah I noticed the NaN errors as well - looks like a data entry error. The coagulantDose field for an entry on June 8th at about 12pm is NaN. 
Tooltip is a better idea, I'll get on that soon.
We should definitely have a meeting. Is Monday morning good? I'll be back in Ithaca starting Wednesday as well.

**Comment by eak24** [comment]
Should we then add a check for NaN so we don't error out? Monday morning works great! I'll email you about it.
